language: ruby
rvm:
  - 1.9.3
env:
  - DEVISE_SECRET=c0ffee
bundler_args: --without development debug
before_install:
  - sed -i /mingw32/d Gemfile.lock
script:
  - RAILS_ENV=test xvfb-run --server-args="-screen 0 1024x768x24" bundle exec rake db:migrate spec
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database multidraft_test' -U postgres
notifications:
  on_success: always
