language: ruby
rvm:
  - 1.9.3
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database multiverse_test' -U postgres
