language: ruby
rvm:
  - 1.9.3
before_install:
  - rm Gemfile.lock
script:
  - RAILS_ENV=test bundle exec rake db:migrate spec
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database multidraft_test' -U postgres
